baseURL = "https://rfdonnelly.github.io/"
languageCode = "en-us"
title = "Rob Donnelly"
theme = "temple"
pygmentsCodefences = true
pygmentsUseClasses = true

[params]
  dateformatpretty = "2006-01-02"

[author]
  name = "Rob Donnelly"
  github = "rfdonnelly"
  gaid = "UA-145317325-1"

[markup]
  [markup.asciidocExt]
    extensions = ["asciidoctor-kroki"]
