baseURL = "https://rfdonnelly.github.io/"
languageCode = "en-us"
title = "Rob Donnelly"
theme = "temple"
pygmentsCodefences = true
pygmentsUseClasses = true

[params]
dataformatpretty = "2006-01-02"

[author]
name = "Rob Donnelly"
github = "rfdonnelly"
gaid = "UA-145317325-1"
