---
title: "Using WSL2"
date: 2020-02-03T22:44:58Z
tags:
- Software
- Docker
- WSL2
- Windows Terminal
- SSH
---

:idprefix:
:idseparator: -

This article documents the setup of WSL2 for local and remote development.
Local development is supported by Docker.
For remote development, WSL2 effectively acts as a bridge.
Remote development is done via SSH with support for X11 forwarding.
This allows X11 applications to be run on the remote host and display on the Windows desktop.

[NOTE]
.CHANGELOG
====
* 2020-11-25 -- Added <<ssh-into-wsl2>>.
* 2020-11-27 -- Changed Docker from edge to stable.
Edge is no longer required.
* 2020-11-27 -- Simplified Windows Terminal settings.
* 2020-11-29 -- Added workaround for older Docker images.
====

== Install WSL2

. Install https://docs.microsoft.com/en-us/windows/wsl/wsl2-install[WSL2]

. Install Ubuntu from the Microsoft Store

. Convert to WSL2
+
 wsl --set-version Ubuntu 2

. Verify WSL version
+
 wsl --list --verbose

== Install Docker

The following will make Docker available from WSL2.

. Download the https://docs.docker.com/docker-for-windows/release-notes/[latest stable release]

. Follow the https://docs.docker.com/docker-for-windows/wsl/[Docker WSL2 instructions]

[NOTE]
====
To run older Docker base images https://github.com/microsoft/WSL/issues/4694[a workaround may be needed].

[source]
.Create `%userprofile%\.wslconfig` with the following content
----
kernelCommandLine = vsyscall=emulate
----
====

== Install Windows Terminal

. Install Windows Terminal from the Microsoft Store{wj}footnote:[Windows Terminal v1.4 as of this writing.]

. Open Windows Terminal

. Edit Settings
+
[source,json]
.profile.json
----
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",

    // Simplify copying
    "copyOnSelect": true,

    // Disable multi-line paste warning
    "multiLinePasteWarning": false,

    // Removed the following characters from the default list to allow double clicking
    // of paths and URLs to select and copy them: '/', '\', '.', ':'
    "wordDelimiters": " ()\"',;<>~!@#$%^&*|+=[]{}~?\u2502",

    "profiles": {
        "defaults": {
            // Make the cursor easier to find
            "cursorShape": "emptyBox",

            // Hide everything by default
            "hidden": true,
        },
        "list": [
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "WSL2",

                // Start WSL like any other profile (i.e. don't use "source")
                // Start in Linux home directory instead of Windows home directory
                "commandline": "wsl.exe ~",

                // WORKAROUND: The right padding is more than it should be.
                // Making it 0 seems to be equivalent to 8 on the left.
                // Also hide the scrollbar so that it doesn't contribute to the padding.
                "padding": "8, 8, 0, 0",
                "scrollbarState": "hidden",
            },
        ]
    },

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": [
        // Make paste work like Linux
        { "command": "paste", "keys": [ "shift+insert" ] }
    ]
}
----

== Setup SSH X11 Forwarding

. Install https://sourceforge.net/projects/vcxsrv[VcXsrc]

. Run XLaunch
.. Set display number to `0`
.. Disable access control
.. Save configuration
.. Open saved configuration to run VcXsrc

. Open a WSL terminal

. Configure `$DISPLAY` by adding the following to your `~/.bashrc`
+
 export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0
+
This sets the DISPLAY to the IP address of the Windows host.

. Configure SSH
+
[source]
.~/.ssh/config
----
Host *
    User <remote-username>
    ForwardX11 yes
    ForwardX11Trusted yes
    ForwardAgent yes
----

. Test
.. SSH
+
 ssh remote-host

.. Run an X11 application
+
 xlogo
+
It should display on your Windows desktop.

// == Setup SSH Port Forwarding
//
// TBD

== Setup Pageant

NOTE: This assumes you manage SSH keys using PuTTY pageant or compatible application.

. Download https://github.com/BlackReloaded/wsl2-ssh-pageant[wsl2-ssh-pageant]
+
 cd ~/.ssh/
 curl -LO https://github.com/BlackReloaded/wsl2-ssh-pageant/releases/download/v1.0.0/wsl2-ssh-pageant.exe
 chmod +x wsl2-ssh-pageant.exe

. Install `socat`
+
 sudo apt-get install socat

. Add `wsl2-ssh-pageant` to your `~/.bashrc`
+
[source,sh]
----
export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0 ]; then
        rm -f $SSH_AUTH_SOCK
        setsid nohup socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:$HOME/.ssh/wsl2-ssh-pageant.exe >/dev/null 2>&1 &
fi
----

== SSH into WSL2

Scott Hanselman has a great article on accessing WSL2 via Windows OpenSSH server titled https://www.hanselman.com/blog/the-easy-way-how-to-ssh-into-bash-and-wsl2-on-windows-10-from-an-external-machine[THE EASY WAY how to SSH into Bash and WSL2 on Windows 10 from an external machine].
However, it only supports Bash.
It doesn't support alternative shells like Zsh.

The trick is to change the Windows OpenSSH server default shell to `C:\Windows\System32\wsl.exe` instead of `C:\Windows\System32\bash.exe`.
This will use whatever shell WSL2 has been configured to use.

[source]
.So instead of
----
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\WINDOWS\System32\bash.exe" -PropertyType String -Force
----

[source]
.Use
----
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\WINDOWS\System32\wsl.exe" -PropertyType String -Force
----
